version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 1999:80
    environment:
      - PMA_ARBITRARY=1